services:
  api:
    build: .
    image: controlnet-deployment:1.0
    ports:
      - "8000:80"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    volumes:
      - ./models:/code/models
      - ./inputs:/code/inputs
      - ./outputs:/code/outputs


